### ISSUE TITLE
Analytics Usage is not submitted because of special characters like '&', 'comma' and ':' in exp_name.

### ISSUE THREAD

**Issue by sravanthimodepu** [vlabs-on-openedx/open-edx-modern-digital-design-lab-iitb#1]
Analytics Usage is not submitted because of special characters like '&', 'comma' and ':' in exp_name.

**Comment by sivashankerN** [comment]
experiment 1 "To Design, implement and Simulate the Full adder using two half adder." has comma, so removed the comma.

**Comment by sivashankerN** [comment]
Reverted back above change.

LDS service needs to be modified as @ksripathi  said.

So I am not fixing other bugs of this lab experiments

**Comment by mrudhvika940** [comment]
Analytics Usage is updated  irrespective of special characters.

**Comment by sravanthimodepu** [comment]
Closing the issue.
